### ISSUE TITLE
Script run method

### ISSUE THREAD

**Issue by Coding-AI-with-html** [Coding-AI-with-html/fls_v1#1]
#  Method in GUI Script Execution with uv

Hello, I managed to run the GUI script, but I have a question regarding the correct approach for the `"go to"` method.  

## Example 1  
**pyproject.toml file:**  
```toml
[project.gui-scripts]
fls-show = "fls_show:main"
```  
This setup runs `__init__.py` when executing with:  
```sh
uv run fls-show
```  
However, if we want to execute `fls_show.py`, which contains the GUI code, we need to modify `__init__.py` as follows:  
```python
from .fls_show import main

if __name__ == "__main__":
    main()
```  

## Example 2  
**pyproject.toml file:**  
```toml
[project.gui-scripts]
fls-show = "fls_show.fls_show:main"
```  
In this case, running `fls-show` is enough for `uv` to understand where to look.  Because I am thinking about ` clarity in things` , or probably better method to have a different names of files.
